flags: {}
extra-package-dbs: []
extra-deps:
- loc-0.1.3.4
packages:
- '.'
- location: languages/go
  extra-dep: true
- location: languages/php
  extra-dep: true
- location: languages/python
  extra-dep: true
- location: languages/typescript
  extra-dep: true
- location: languages/json
  extra-dep: true
- location: languages/ruby
  extra-dep: true
- location: languages/haskell
  extra-dep: true
resolver: lts-12.20
