#!/bin/bash
#/ Usage: script/update-tree-sitter
#/
#/ Update tree-sitter and all associated tree-sitter-* language submodules.

set -e
cd $(dirname "$0")/..

for item in $(ls vendor); do
  pushd $item
  git checkout master && git pull origin master
  popd
done

